sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/ALGPHELLO/android_device_honor_msm8937_64.git device/android/msm8937_64
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_msm8937_64-eng && make -j32 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/msm8937_64/recovery.img $HOME/twrp/TWRP-$version-msm8937_64-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: ALGPHELLO/android_device_honor_msm8937_64
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/